### ISSUE TITLE
Error on test

### ISSUE THREAD

**Issue by BrianWestlake** [silicon-valley-data-science/RNN-Tutorial#7]
Getting an error on running the test script:
$ python $RNN_TUTORIAL/src/tests/train_framework/tf_train_ctc_test.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/home/brian/RNN-Tutorial/src/tests/train_framework/tf_train_ctc_test.py", line 8, in <module>
    import train_framework.tf_train_ctc as tf_train
  File "/home/brian/RNN-Tutorial/src/train_framework/tf_train_ctc.py", line 17, in <module>
    from models.RNN.utils import create_optimizer
  File "/home/brian/RNN-Tutorial/src/models/RNN/utils.py", line 5, in <module>
    from utils.set_dirs import get_conf_dir
ImportError: No module named set_dirs

Environment is Ubuntu 16.04, CUDA 8.0 and a GTX 1080

**Comment by BrianWestlake** [comment]
Yes, the set_dirs.py file is present in my utils directory

**Comment by mrubashkin-svds** [comment]
@BrianWestlake can you try running the code with a manually set PYTHONPATH:
```
os.environ['PYTHONPATH']='/home/brian/RNN-Tutorial/src:`
```
Could you either be launching `python $RNN_TUTORIAL/src/tests/train_framework/tf_train_ctc_test.py` from within `/home/brian/RNN-Tutorial/src/models/RNN/` directory, thereby adding it to the PATH. Or perhaps have you added an extra directory to your path, causing the true location of `home/brian/RNN-Tutorial/src/utils/set_dirs.py` to not be used?

**Comment by chronoglass** [comment]
ran into the same problem, and indeed changing the utils name in each of the scripts, and changing the env line at the top from python3 to just python(not sure if this was needed, will run again after changing it back and report), and the dir name (and a pip install click in my virtualenv later) I was up and running

dir change:
$RNN_TUTORIAL/src/utils --> $RNN_TUTORIALS/src/utilities

text changes:
FILE: $RNN_TUTORIALS/src/train_framework/tf_train_ctc.py 
line 19 - from utils.set_dirs import get_conf_dir, get_model_dir --> from utilities.set_dirs import get_conf_dir, get_model_dir 
line 20 - import utils.gpu as gpu_tool --> import utilities.gpu as gpu_tool

FILE: $RNN_TUTORIALS/src/data_manipulation/datasets.py
line 11 - from utils.set_dirs import get_data_dir --> from utilities.set_dirs import get_data_dir

FILE: $RNN_TUTORIALS/src/models/RNN/utils.py
line 5 - from utils.set_dirs import get_conf_dir -->  from utilities.set_dirs import get_conf_dir

FILE: $RNN_TUTORIALS/src/utilities/set_dirs.py
line 1 - #!/usr/bin/env python3 -> #!/usr/bin/env python
